all:
	g++ -I src/include -L src/lib -o TetrAI code/model/*.cpp code/tetris_lib/*.cpp code/scene/*.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf

test_1:
	g++ -I src/include -L src/lib -o main test.cpp

test_reg:
	g++ -I src/include -L src/lib -o main AIHeuristics.cpp AIModel.cpp Collision.cpp Piece.cpp

normal:
	g++ -I src/include -L src/lib -o main *.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf

# all: clean compile link run

# test: compile link run

# compile:
# 	g++ -I src/include -L src/lib *.o -o main *.cpp 

# link:
# 	g++ -lmingw32 -lSDL2main -lSDL2

# clean:
# 	del *.o

# run:
# 	main.exe


