
const int MENU_DEFAULT = 0;
const int MENU_BATTLE_SELECT = 1;
const int MENU_TRAIN_SELECT = 2;

const int MENU_BATTLE_PLAYER_VS_CUSTOM = 10;
const int MENU_BATTLE_PLAYER_VS_PREBUILT = 11;
const int MENU_BATTLE_CUSTOM_VS_PREBUILT = 12;

const int MENU_TRAIN_BATTLE_ROYALE = 20;
const int MENU_TRAIN_SPRINT_CHALLENGE = 21;
const int MENU_TRAIN_SURVIVAL_CHALLENGE = 22;

const int MENU_SETTINGS = 30;

const int TRAIN_CANCEL = 0;
const int TRAIN_CONFIRM = 1;